### PR TITLE
Use bash syntax for entrypoint

### PR DESCRIPTION
**Pull request by carmenbianca**
I *think* that this may fix the issue described in #3 where you can't provide multiple arguments.

### CODE REVIEW

**Comment by mxmehl** [comment]
Does not work unfortunately when testing. It even does not fail in some cases although the command is not recognised... https://github.com/fsfe/reuse-action/runs/484736354

**Comment by mxmehl** [comment]
@carmenbianca Would you have time to find a way to support multiple arguments? Is the tool somehow related to that in a sense that it could be modified to deal with subcommand + arguments in one string?

**Comment by carmenbianca** [comment]
As far as I know, that's not really something that is supported :(

**Comment by carmenbianca** [comment]
Going to look into this for the next hour or two. Might not find anything, but :shrug:

**Comment by carmenbianca** [comment]
Works on https://github.com/carmenbianca/reuse-action/runs/611879436?check_suite_focus=true

https://github.com/carmenbianca/reuse-action/blob/39454c55e9d17993f98dce1a0e5a11b220eb8457/.github/workflows/main.yml

The trick: Don't use a custom-defined variable, but just use `args`.

Source: https://github.com/pandoc/pandoc-action-example

I'm going to try to clean up things a little once I get Docker running locally. Fedora and Docker have a rocky relationship…

**Comment by mxmehl** [comment]
I am purely amazed. Thanks for finding this out and cleaning things up!

**Comment by carmenbianca** [comment]
Overriden by #7

**Pull request closed without merging**
